courses/urls.py
from django.urls import path

from . import views


app_name = "courses"
urlpatterns = [
    path("", views.CourseListView.as_view(), name='list'),
    path("courses/<int:pk>/", views.CourseDetailView.as_view(), name="detail"),
#    path("courses/<int:course_pk>/<int:step_pk>/", views.step_detail, name='step'),
    path("courses/<int:course_pk>/<int:step_pk>/", views.StepDetailView.as_view(), name='step'),
]

learners_cafe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import HelloView, HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello/", HelloView.as_view(), name="hello"),
    path("", HomeView.as_view(), name="home"),
    path("courses/", include("courses.urls")),
]


urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()


    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default="")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["order"]

courses/views.py
from django.views.generic import ListView, DetailView

from .models import Course, Step


class CourseListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course


from django.shortcuts import render, get_object_or_404


# def step_detail(request, **kwargs):
#     course_pk = kwargs["course_pk"]
#     step_pk = kwargs["step_pk"]
#     step = get_object_or_404(Step, course=course_pk, pk=step_pk)
#     return render(request, "courses/step_detail.html", {"step": step})

class StepDetailView(DetailView):

    model = Step
    query_pk_and_slug=True
    slug_field = 'course'
    slug_url_kwarg = 'course_pk'
    pk_url_kwarg = 'step_pk'

learners_cafe/views.py
from django.views import View
from django.views.generic import TemplateView
from django.http import HttpResponse


class HelloView(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse("Hello World!")


class HomeView(TemplateView):
    template_name = "home.html"

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    {{ course.description }}
    <section>
        {% for step in course.step_set.all %}
            <h3><a href="{% url "courses:step" course_pk=step.course.pk step_pk=step.pk %}">{{ step.title|title }}</a></h3>
        {{ step.description }}
        {% endfor %}
    </section>
</article>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}

{% block title %}
    Available Courses
{% endblock %}

{% block content %}
<ul>
{% for course in object_list %}
    <li><a href="{% url "courses:detail" pk=course.pk %}">{{ course.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block content %}
<article>
    <h2><a href="{% url "courses:detail" pk=object.course_id %}">{{ object.title }}</a></h2>
    {{ object.description|linebreaks }}
    <section>
        {{ object.content|linebreaks }}
    </section>
</article>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block content %}
<h1>Welcome to Learner's Cafe!</h1>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/layout.css" %}">
</head>
<body>
    <nav>
        <a href="{% url "home" %}">Home</a>
        <a href="{% url "courses:list" %}">Courses</a>
    </nav>
    <div>
    {% block content %}{% endblock %}
    </div>
</body>
</html>